server:
  port: 9898
  servlet:
    session:
      cookie:
        name: AUTH_SERVER_SESSION_ID
        http-only: true

spring:
  application:
    name: authorization-server
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML #LEGACYHTML5
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 3000ms
      connect-timeout: 5000
      client-type: LETTUCE
      lettuce:
        pool:
          max-wait: 800ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-active: 5 #连接池最大连接数（使用负值表示没有限制）
          min-idle: 3 #连接池中的最小空闲连接
          max-idle: 5 #连接池中的最大空闲连接
  security:
    oauth2:
      authorizationserver:
        multiple-issuers-allowed: false
        issuer: http://127.0.0.1:9898
        endpoint:
          authorizationUri: /oauth/authorize
          deviceAuthorizationUri: /oauth/device_authorization
          deviceVerificationUri: /oauth/device_verification
          tokenUri: /oauth/token
          jwkSetUri: /oauth/jwks
          tokenRevocationUri: /oauth/revoke
          tokenIntrospectionUri: /oauth/introspect
          oidc:
            logoutUri: /connect/logout
            clientRegistrationUri: /connect/register
            userInfoUri: /userinfo

logging:
  config: classpath:logback/logback-spring.xml
  level:
    root: debug
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    io.lettuce.core: off
    org.springframework.data.redis.core: off
